    show_debug_message(global.save_directory)
    if variable_global_exists("altsave")
        global.altsave = (!global.altsave)
    else
        global.altsave = 0
    slot_prefix = gml_Script_scr_get_save_slot_prefix(global.active_save_slot)
    if (!global.altsave)
        file = file_text_open_write((global.save_directory + slot_prefix) + "SaavoGame23-2.sav")
    else
        file = file_text_open_write(((global.save_directory + slot_prefix + "_alt_") + "SaavoGame23-2.sav"))
    show_debug_message("pwease" + global.save_directory)
    global.save_id += 1
    file_text_write_real(file, global.save_id)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Hello, human. Cheating isn't really fun when it's that easy, is it?")
    file_text_writeln(file)
    file_text_write_string(file, "Change whatever you want if it helps to makes you feel good.")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "!! Edit at your own risk !!")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Game Version")
    file_text_writeln(file)
    file_text_write_string(file, "1.42")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Room")
    file_text_writeln(file)
    file_text_write_real(file, argument0)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Deaths")
    file_text_writeln(file)
    file_text_write_real(file, global.save_deaths)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Difficulty")
    file_text_writeln(file)
    file_text_write_real(file, global.save_difficulty)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Played Voice Lines")
    file_text_writeln(file)
    scr_sv_list_string(global.save_played_locakeys)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Difficulty Settings Unlocked")
    file_text_writeln(file)
    file_text_write_real(file, global.save_difficulty_selection_unlocked)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Deaths")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_deaths)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Playtime")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_playtime)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Unlocked")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_unlocked)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Beaten On Difficulty")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_beaten_on_difficulty)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Beaten On Difficulty Underwater")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_beaten_on_difficulty_underwater)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Autodiff-Playtime")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_autodiff_playtime)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Data: Autodiff-Deaths")
    file_text_writeln(file)
    scr_sv_list_real(global.li_lvldat_autodiff_difficulty)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Autodiff Levels Till Increase")
    file_text_writeln(file)
    file_text_write_real(file, global.save_levels_you_have_to_beat_till_difficulty_can_be_increased_again)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Timer Game")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_timer_game)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Timer Chapter")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_timer_chapter)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Current Chapter")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_current_chapter)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Timer Level")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_timer_level)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Exploration Mode")
    file_text_writeln(file)
    file_text_write_real(file, global.save_exploration_mode)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Collected Exploration Points")
    file_text_writeln(file)
    scr_sv_list_string(global.save_collected_exploration_points)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Game Speed")
    file_text_writeln(file)
    file_text_write_real(file, global.save_game_speed)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Training Mode")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_training_mode)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Unlocked Dialogs")
    file_text_writeln(file)
    scr_sv_list_string(global.save_unlocked_dialogs)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Hat")
    file_text_writeln(file)
    file_text_write_real(file, global.save_equipped_hat)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Heart Fixed")
    file_text_writeln(file)
    file_text_write_real(file, global.save_heart_fixed)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Final Credits Reached")
    file_text_writeln(file)
    file_text_write_real(file, global.save_final_final_credits_reached)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Pump Inverted")
    file_text_writeln(file)
    file_text_write_real(file, global.save_pump_is_inverted)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Speedrun Is Still Legit")
    file_text_writeln(file)
    file_text_write_real(file, global.save_speedrun_is_still_legit)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Anger Game Level")
    file_text_writeln(file)
    file_text_write_real(file, global.save_anger_game_level)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Anger Game XP")
    file_text_writeln(file)
    file_text_write_real(file, global.save_anger_game_xp)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Auto Difficulty")
    file_text_writeln(file)
    file_text_write_real(file, global.save_auto_difficulty)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Fixed Jump Height")
    file_text_writeln(file)
    file_text_write_real(file, global.save_fixed_jump_height)
    repeat (2)
        file_text_writeln(file)
    file_text_close(file)
    return;

