    file = file_text_open_write(global.save_directory + "SettoIngs23-2.set")
    file_text_write_string(file, "Hello, human. Welcome to the advanced version of the settings menu.")
    file_text_writeln(file)
    file_text_write_string(file, "Make sure you know what you're doing before you change anything here.")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "!! Edit at your own risk !!")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Game Version")
    file_text_writeln(file)
    file_text_write_string(file, "1.42")
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Gamepad Rumble")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_gamepad_rumble)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Volume Master")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_volume_master)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Volume Voice")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_volue_voice)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Volume Music")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_volue_music)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Volume SoundFx")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_volue_fx)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Post Processing")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_post_processing)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Visual Detail")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_visual_details)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Subtitles")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_subtitles)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Window Mode")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_window_mode)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Text Language")
    file_text_writeln(file)
    file_text_write_string(file, global.setting_loca_text)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Audio Language")
    file_text_writeln(file)
    file_text_write_string(file, global.setting_loca_voice)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Screenshake")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_screenshake)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Auto Difficulty")
    file_text_writeln(file)
    file_text_write_real(file, global.save_auto_difficulty)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Subtitle Size")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_subtitle_size)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Gamepad Dead Zones")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_gp_dead_zones)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Speedrun Timer")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_speedrun_timer_game)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Chapter Timer")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_speedrun_timer_chapter)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Level Timer")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_speedrun_timer_level)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "V-Sync")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_vsync)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "AI Predictions")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_show_ai_predictions)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Timing Method")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_timing_method)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Sleep Margin")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_sleep_margin)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Show FPS")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_speedrun_show_fps)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Color Scheme")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_color_scheme)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Squid Opacity")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_squid_opacity)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Squid Stay In Back")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_squid_stay_in_background)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Squid Facial Expessions")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_squid_facial_expressions)
    repeat (2)
        file_text_writeln(file)
    file_text_write_string(file, "Font Nr")
    file_text_writeln(file)
    file_text_write_real(file, global.setting_font_nr)
    repeat (2)
        file_text_writeln(file)
    file_text_close(file)
    return;

